# Generated by Django 6.0.7 on 2026-07-28 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20260723_0752'),
        ('notifications', '0002_notification_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type', '-created_at'], name='notificatio_user_id_3b3832_idx'),
        ),
    ]
