services:
  db:
    image: postgres:18-alpine
    ports:
      - "127.0.0.1:${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:alpine
    restart: always
    expose:
      - "6379"

  backend:
    build: ./backend
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 core.asgi:application"
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - backend

  celery:
    build: ./backend
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - redis
      - backend

  celery-beat:
    build: ./backend
    command: celery -A core beat --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - redis
      - backend

  gateway:
    image: nginx:1.30.4-alpine-slim
    volumes:
        - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: