# Generated by Django 5.2.4 on 2026-04-16 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formresponse_alter_answer_response_delete_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
