# Generated by Django 5.2.4 on 2026-04-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('parent', 'Родитель'), ('user', 'Пользователь'), ('teacher', 'Преподаватель'), ('admin', 'Администратор')], default='user', max_length=10),
        ),
    ]
