# Generated by Django 5.2.4 on 2026-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='one_question_per_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='require_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='show_results_after',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='timer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='timer_seconds',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='question_media/'),
        ),
    ]
