# Generated by Django 5.2.4 on 2026-04-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_one_question_per_page_form_require_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_email', models.EmailField(blank=True, max_length=254)),
                ('respondent_school', models.CharField(blank=True, max_length=200)),
                ('respondent_grade', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('auto_score', models.PositiveIntegerField(default=0)),
                ('manual_score', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.form')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formresponse'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
