# Generated by Django 5.2.4 on 2026-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_form_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='manual_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слаг для URL'),
        ),
    ]
