# Generated by Django 5.2.4 on 2026-04-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_answer_is_reviewed_answer_manual_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Правильный ответ'),
        ),
    ]
