# Generated by Django 5.2.4 on 2026-05-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='one_time_participation_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='survey_for_authorized_users',
            field=models.BooleanField(default=False),
        ),
    ]
