# Generated by Django 5.2.4 on 2026-04-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_category_color_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='form_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
