# Generated by Django 6.0.3 on 2026-06-09 15:28

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_news_form_id_news_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.news_image_path),
        ),
    ]
