# Generated by Django 6.0.7 on 2026-07-23 07:52

from django.db import migrations


def create_default_categories(apps, schema_editor):

    Category = apps.get_model('news', 'Category')
    
    default_categories = [
        {"name": "Новости", "slug": "novosti"},
        {"name": "Мероприятие", "slug": "meropriyatie"}
    ]

    for category_name in default_categories:
        Category.objects.get_or_create(name=category_name["name"], defaults={"slug": category_name["slug"]})


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_image'),
    ]

    operations = [
        migrations.RunPython(create_default_categories)
    ]
