# Generated by Django 6.0.7 on 2026-08-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='form_slug',
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
