# Generated by Django 5.2.4 on 2026-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studygroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
