# Generated by Django 6.0.7 on 2026-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('teacher', 'Преподаватель'), ('admin', 'Администратор')], default='user', max_length=10),
        ),
    ]
