# Generated by Django 6.0.7 on 2026-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_groupmembership_studygroup_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг для публичной страницы'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('completed', 'Прошёл модуль'), ('failed', 'Не прошёл модуль'), ('left', 'Покинул')], default='active', max_length=10),
        ),
    ]
