# Generated by Django 6.0.7 on 2026-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_studygroup_slug_alter_groupmembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала занятий'),
        ),
    ]
