# Generated by Django 6.0.7 on 2026-10-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_studygroup_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='students',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
