# Generated by Django 5.2.4 on 2026-04-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_color_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
