# Generated by Django 5.2.4 on 2026-05-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_question_correct_answer'),
        ('news', '0007_news_form_id_news_form_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='form_id',
        ),
        migrations.AddField(
            model_name='news',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='forms.form'),
        ),
    ]
